<?php

namespace App\Services;


/**
 * QrPayload — the single place that turns whatever a camera decoded into a
 * trusted (branch, table) pair.
 *
 * The scanner hands over raw bytes from the physical world: a genuine table QR,
 * a QR from a different system, a photo of a tampered sticker, or a hand-typed
 * URL. None of it is trustworthy, and the parsing used to live inline in
 * AuthController::processQr where the loose checks let several malformed
 * payloads through to a real Dine-In session:
 *
 *   branch_id[]=1&table=5           -> branch_id arrived as an ARRAY and still
 *                                      resolved to branch 1
 *   branch_id=1 OR 1=1&table=5      -> PHP's int cast made this branch 1
 *   branch_id=1&table[]=5           -> session('table_number') became an array,
 *                                      crashing order placement much later
 *   branch_id=1&table=999...(500)   -> accepted, then blew up on insert because
 *                                      orders.table_number is string(10)
 *   branch_id=1&table=<script>...   -> stored verbatim as the table number
 *
 * Every one of those is now rejected here, before any session state is written.
 *
 * The canonical table number is uppercase alphanumeric, 1-10 characters — the
 * same shape AdminController::qrTableCard() and App\Services\TableEntry already
 * enforce, and it fits orders.table_number (string(10)). Normalising here means
 * a scan and a typed table code for the same table produce the identical value
 * rather than "a1" versus "A1".
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY THE QR URL IS DELIBERATELY NOT SIGNED
 * ─────────────────────────────────────────────────────────────────────────────
 * This class does not CRYPTOGRAPHICALLY sign the payload — there is no HMAC
 * proving a given URL was generated by us. What it does now carry is the
 * table's permanent code, as `k`: TableEntry::validate() requires `k` to match
 * restaurant_tables.code for that branch+table, so a QR photographed before an
 * admin regenerated that table's code stops opening a session the moment the
 * code rotates — the same escape hatch the typed code already had. An
 * unsigned-but-code-checked URL is the deliberate team position; the reasoning
 * against a full signature still stands and is set out below.
 *
 * The reasoning:
 *
 *   1. A signature would not solve the actual problem. The table QR is printed
 *      once and left on the table permanently, so it can be photographed. A
 *      photographed signed URL is just as replayable as a photographed unsigned
 *      one — signing raises the bar for someone INVENTING a URL, not for the far
 *      more likely person who simply took a picture of a real one.
 *
 *   2. The real protection is the session lifecycle, not cryptography. A dine-in
 *      session now ENDS BY ITSELF — when the table's order completes, and after
 *      App\Services\TableOccupancy::INACTIVITY_MINUTES of silence — it is rate
 *      limited so it cannot be opened in a loop, and it is visible to staff on
 *      the Occupied Tables panel the whole time it is open. A replayed URL
 *      therefore buys a short, throttled, staff-visible session rather than a
 *      standing key to the room, regardless of how the URL was obtained.
 *
 *      (This point used to read "at most one live session per table, and only
 *      the first gets it". That exclusivity is gone on purpose: four people at
 *      one table all scan, and refusing the second, third and fourth was a
 *      worse failure than the one it prevented. Occupancy is now SHARED — later
 *      scans JOIN the party's session — so the controls above, not exclusion,
 *      are what bound a replayed QR.)
 *
 *   3. The cost is real and the benefit is not. Adding a signature would
 *      invalidate every table card already printed and placed, forcing a full
 *      reprint across all branches, in exchange for the narrow gain in (1).
 *
 *   4. Staff are the backstop. Dine-in happens in a room with staff in it. A
 *      table showing an order nobody is sitting at is visible, and the staff
 *      portal has a "clear table" action for exactly that.
 *
 * Historical note: an HMAC helper (App\Services\TableCode) once existed for the
 * old printed fallback code, and after that a staff-issued single-use code
 * (App\Services\TableAccessCode) took over the job. Both have since been
 * DELETED — the permanent code in App\Services\TableEntry is now the only
 * table credential — do not go looking for either file. Nothing in this
 * codebase signs table identifiers any more.
 */
class QrPayload
{
    /**
     * A QR code physically cannot carry much more than this, so anything larger
     * is not a table QR and is not worth parsing.
     */
    public const MAX_PAYLOAD_LENGTH = 2048;

    /** Attempts allowed per IP per minute before scan submissions are throttled. */
    public const MAX_ATTEMPTS = 20;

    /**
     * Parse and validate a scanned payload.
     *
     * @return array{ok: bool, branch?: Branch, table_number?: string, error?: string}
     */
    public static function parse(?string $payload): array
    {
        $payload = trim((string) $payload);

        if ($payload === '') {
            return self::fail('That QR code could not be read. Please try scanning again.');
        }

        if (strlen($payload) > self::MAX_PAYLOAD_LENGTH) {
            return self::fail('That QR code is not a Peachy table code.');
        }

        [$branchId, $tableNumber, $code] = self::extract($payload);

        return self::fromParts($branchId, $tableNumber, $code);
    }

    /**
     * Validate an already-separated branch/table pair.
     *
     * Used directly by the menu route, because a phone's built-in camera app
     * opens the QR's URL (/customer/menu?branch_id=..&table=..) rather than
     * posting the payload to the scanner. That landing has to apply exactly the
     * same checks, or it becomes an unvalidated back door into any branch and
     * table by simply editing the address bar.
     *
     * @return array{ok: bool, branch?: Branch, table_number?: string, error?: string}
     */
    public static function fromParts($branchId, $tableNumber, $code = null): array
    {
        /*
         * DELEGATED, ON PURPOSE.
         *
         * This method used to carry its own copy of the branch/table checks.
         * That was one of three copies in the codebase, and three copies of a
         * refusal list is how one of them quietly ends up shorter than the
         * others. Every dine-in door — this one, the typed permanent code, and
         * the /customer/menu URL landing — now decides refusals in exactly one
         * place, App\Services\TableEntry::validate().
         *
         * The malformed-payload guards that used to live here (is_scalar
         * against array injection, ctype_digit against "1 OR 1=1", hex, floats,
         * negatives and zero, the 1-10 uppercase-alphanumeric table rule)
         * moved there verbatim. Parsing a payload into a candidate pair is
         * still this class's job; deciding whether that pair is acceptable is
         * not.
         *
         * The QR's `k` parameter — the table's permanent code — rides through
         * here untouched to TableEntry::validate(), which is where the code
         * rule lives for every door.
         */
        return TableEntry::validate($branchId, $tableNumber, $code);
    }

    // ══════════ internals ══════════

    /**
     * Pull the raw branch/table/code values out of any of the three shapes the
     * scanner has ever produced: a full URL, a JSON object, or a bare query
     * string. Values are returned untouched — validation happens after. The
     * code is the QR's `k` parameter (the table's permanent code).
     *
     * @return array{0: mixed, 1: mixed, 2: mixed}
     */
    private static function extract(string $payload): array
    {
        if (filter_var($payload, FILTER_VALIDATE_URL)) {
            $parts = parse_url($payload);

            if (empty($parts['query'])) {
                return [null, null, null];
            }

            parse_str($parts['query'], $params);

            return [
                $params['branch_id'] ?? null,
                $params['table'] ?? $params['table_number'] ?? null,
                $params['k'] ?? null,
            ];
        }

        $decoded = json_decode($payload, true);

        if (is_array($decoded)) {
            return [
                $decoded['branch_id'] ?? $decoded['branchId'] ?? null,
                $decoded['table'] ?? $decoded['table_number'] ?? null,
                $decoded['k'] ?? $decoded['code'] ?? null,
            ];
        }

        parse_str($payload, $params);

        return [
            $params['branch_id'] ?? null,
            $params['table'] ?? $params['table_number'] ?? null,
            $params['k'] ?? null,
        ];
    }

    private static function fail(string $message): array
    {
        return ['ok' => false, 'error' => $message];
    }
}
