<?php

namespace Tests\Feature;

use App\Models\Branch;
use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

/**
 * Phase 3b F5 — the CSV formula-injection guard (App\Support\Csv::cell(), see
 * AnalyticsIntelligenceAndExportTest TEST 21) was applied to every DATA row of
 * all three exports, but not to the metadata HEADER block of two of them:
 * exportInventory's ['Branch', $branchName] / ['Generated by', <user name>]
 * and exportOrders' same two lines. exportAnalytics already wrapped both.
 *
 * Both values are user-controlled — branch names come from storeBranch,
 * account names from storeUser — so a branch or account named e.g.
 * =HYPERLINK("http://evil","Click") was evaluated as a formula the moment
 * the exported file was opened, same as an unguarded ingredient name.
 */
class AdminCsvExportMetadataFormulaGuardTest extends TestCase
{
    use DatabaseTransactions;

    private const PREFIX = 'F5GuardTest';

    private function branchWithFormulaName(): Branch
    {
        return Branch::create([
            'name'       => '=HYPERLINK("http://evil.example","Click") ' . self::PREFIX . ' ' . uniqid(),
            'code'       => 'F5-' . strtoupper(substr(uniqid(), -6)),
            'address'    => '123 Test Street',
            'is_active'  => true,
        ]);
    }

    private function adminWithFormulaName(): User
    {
        return User::create([
            'name'      => '=cmd|/c calc!A1 ' . self::PREFIX . ' ' . uniqid(),
            'email'     => 'f5-admin-' . uniqid() . '@example.test',
            'password'  => bcrypt('AdminReal!Pass1'),
            'role'      => 'admin',
            'is_active' => true,
        ]);
    }

    private function assertEveryCellCarryingIsNeutralised(string $csv, string $needle, string $label): void
    {
        $handle = fopen('php://memory', 'r+');
        fwrite($handle, $csv);
        rewind($handle);

        $seen = false;
        while (($cells = fgetcsv($handle)) !== false) {
            foreach ($cells as $cell) {
                if (str_contains((string) $cell, $needle)) {
                    $seen = true;
                    $this->assertSame(
                        "'",
                        substr((string) $cell, 0, 1),
                        "{$label} cell carrying '{$needle}' must be neutralised with a leading single quote"
                    );
                }
            }
        }
        fclose($handle);

        $this->assertTrue($seen, "{$label} value must actually appear in the export");
    }

    public function test_inventory_export_metadata_header_is_neutralised(): void
    {
        $branch = $this->branchWithFormulaName();
        $admin = $this->adminWithFormulaName();

        $response = $this->actingAs($admin, 'admin')
            ->withSession(['selected_branch_id' => $branch->id])
            ->get(route('admin.inventory.export'));

        $response->assertOk();
        $csv = $response->streamedContent();

        $this->assertEveryCellCarryingIsNeutralised($csv, $branch->name, 'Branch header row');
        $this->assertEveryCellCarryingIsNeutralised($csv, $admin->name, 'Generated by header row');
    }

    public function test_orders_export_metadata_header_is_neutralised(): void
    {
        $branch = $this->branchWithFormulaName();
        $admin = $this->adminWithFormulaName();

        $response = $this->actingAs($admin, 'admin')
            ->withSession(['selected_branch_id' => $branch->id])
            ->get(route('admin.export.orders'));

        $response->assertOk();
        $csv = $response->streamedContent();

        $this->assertEveryCellCarryingIsNeutralised($csv, $branch->name, 'Branch header row');
        $this->assertEveryCellCarryingIsNeutralised($csv, $admin->name, 'Generated by header row');
    }

    /**
     * The analytics export already had this guard (both call sites) — pinned
     * here as the control so a future pass can trust that comparison instead
     * of re-deriving it.
     */
    public function test_analytics_export_metadata_header_was_already_guarded(): void
    {
        $branch = $this->branchWithFormulaName();
        $admin = $this->adminWithFormulaName();

        $response = $this->actingAs($admin, 'admin')
            ->withSession(['selected_branch_id' => $branch->id])
            ->get(route('admin.analytics.export', [
                'date_from' => now()->subDay()->format('Y-m-d'),
                'date_to'   => now()->format('Y-m-d'),
            ]));

        $response->assertOk();
        $csv = $response->streamedContent();

        $this->assertEveryCellCarryingIsNeutralised($csv, $branch->name, 'Branch header row');
        $this->assertEveryCellCarryingIsNeutralised($csv, $admin->name, 'Generated by header row');
    }
}
